name: PR Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4		
        with:
          python-version: '3.10' # install the python version needed		  
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install openai
      - name: execute py script 
        env:
           ACCOUNT_GITHUB_TOKEN: ${{ vars.ACCOUNT_GITHUB_TOKEN }}
           REPO_NAME: ${{ vars.REPO_NAME }}
           REPO_OWNER: ${{ vars.REPO_OWNER }}
           SECRET_GITHUB_KEY: ${{ secrets.SECRET_GITHUB_KEY }}
           SECRET_OPENAI_TOKEN: ${{ secrets.SECRET_OPENAI_TOKEN }}
        run: python .github/workflows/pr_reviewer.py